### ISSUE TITLE
zip files are always excluded, even though field is blank

### ISSUE THREAD

**Issue by gbcox** [baptistecdr/aria2-integration#294]
Using current Fx version.  When trying to download zip files, notice that they are always excluded and downloaded by Fx.

**Comment by baptistecdr** [comment]
I found that editing Excluded Protocols/Sites/File Types sometimes does not work. It should be fixed.
I also found that when the zip file is instantly downloaded, capturing does not work, it should be fixed.

You can download this dev version here: https://github.com/baptistecdr/aria2-integration/actions/runs/6599148215 import it in about:debugging#/runtime/this-firefox

Let me know if you still experiencing some problems.

**Comment by gbcox** [comment]
Yes, that appears to have fixed the issue.  Thanks for the quick response.
