### ISSUE TITLE
[Feature request] Add identifier

### ISSUE THREAD

**Issue by FahimAnayet** [baptistecdr/aria2-integration#296]
If it is possible please add some identifier so we can understand if it is downloading or not. For example, when a file is downloading the icon may show a superscript 1 or a dot.
Thank you

**Comment by baptistecdr** [comment]
Hello @FahimAnayet ,

I just release a new version of the extension that show the number of active downloads: 

<img width="37" alt="Capture d’écran 2023-11-11 à 13 56 33" src="https://github.com/baptistecdr/aria2-integration/assets/11665396/d594502d-f675-4a09-9454-fa3fb0990ed0">

Have a nice day,
baptistecdr
