### ISSUE TITLE
Fx files not saving, receive error

### ISSUE THREAD

**Issue by gbcox** [baptistecdr/aria2-integration#321]
Hi, I noticed something regarding files saved from Fx directory.  For example I use the Nighttab extension, and when saving the configuration, it suppose to go to a directory on my system.  Also, if I'm printing a page and saving the output as a PDF file, it is also suppose to go to the target directory.  

In both these instances, these files are sent over to the aria2 extension and processing fails.  I receive the message:
"An error occurred when adding a file to local host".

I tried adding "localhost" and "127.0.0.1" to the exclude host list, but that didn't work.  Nighttab exports a .json file, so I was able to specify that to get around the issue, but there may be times when I want to download .json or probably more often .pdf files from other sites, so that probably isn't the best solution.  

Any ideas?  Is there another another way of telling aria2 to ignore files that are local?  Thanks much!

P.S.  I also noticed that I can't enter a comma to separate multiple entries on any of the exclude lists as shown in the examples.

**Comment by baptistecdr** [comment]
Hi @gbcox ,

I have fixed the input problem for excluded options in the linked Pull Request above.

When you are viewing a PDF in Firefox, it uses pdf.js and if you save it, it will use the `blob` protocol.
When you are viewing local file and you try to download it, it will use the `file` protocol.
When you are exporting nightTab data, it uses `data` protocol.

**Comment by gbcox** [comment]
Hi, thank you so much for the quick response.  I tested and it appears to be working.  However, I noticed for nighttab, I needed specifically exclude "data" in the protocols.  Is that what you intended?  I "printed" a pdf to file and it saved correctly without specifically excluding the "blob" protocol.  I haven't saved anything with the "file" protocol.  

I can certainly exclude the "data" protocol in the config, but can't think of a valid situation where that would be used for aria2.  Not many people are going to know that it isn't compatible with aria2.  Maybe it would be a better idea to just automatically exclude protocols that aren't compatible.  I would view the exclude protocols option to be used for some reason if people wanted to exclude a protocol that was compatible.   Does that make sense?  

Anyway, thanks again for your quick response.  Much appreciated.

**Comment by baptistecdr** [comment]
You're welcome and sorry for the bug.

Yeah, I can add to the protocols ignore list data, file and blob. I will do that next week.

**Comment by gbcox** [comment]
No worries.  Thanks again for the quick response!

**Comment by baptistecdr** [comment]
The following protocols `data`, `file` & `blob` are now excluded in 4.8.0
