### ISSUE TITLE
[Bug] Firefox Extension Stopped Working Properly

### ISSUE THREAD

**Issue by LeeThompson** [baptistecdr/aria2-integration#359]
This stopped working, no error messages so unable to troubleshoot exactly what the issue is but it can no longer add/monitor/remove jobs.

Aria2 is running 1.36.0 in a docker container.  (Works fine with other Aria2 integrators and directly in the web browser.)

Browser is running Firefox x64 120.0.1

**Comment by baptistecdr** [comment]
Hello @LeeThompson ,

Strange, I also have Firefox 120.0.1 and no problems.

Could you navigate to `about:debugging#/runtime/this-firefox` and click on `Examine` for Aria2 Integration.

Send some links to Aria2 Integration and check if there is any error showing off in the console.

**Comment by LeeThompson** [comment]
My Aria2 instances are not on the same machine, they are on the LAN in docker instances on my NAS boxes.

Looks like a Cross Origin Request issue and the other problem is they are not using https and I have this extension set  with the secure connection box clear but it is forming them as https anyway.

(I've removed part of the resource name for privacy purposes)

Lot of these:
```

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria1:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria2:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).
```

**Comment by baptistecdr** [comment]
Sorry if you already did that, but did you try to delete the server in the configuration and recreate it ?

**Comment by LeeThompson** [comment]
Yes, more than once.

**Comment by baptistecdr** [comment]
Huum, do you have any extension/option that might enforce HTTPS instead of HTTP?

**Comment by LeeThompson** [comment]
I do not.  In fact, I tried using a different Aria2 add-on and it works fine but I don't like it nearly as much as this one.

**Comment by baptistecdr** [comment]
Could you go back to `about:debugging#/runtime/this-firefox` and click on `Examine` for Aria2 Integration.

In Console Tab:

```js
const storage = await browser.storage.sync.get(null);
JSON.parse(storage.options) 
```

Does your configuration seems correct? Most important is `secure: false` for your server.

Also, in Network tab, does any request seems off ? (espically in response)

**Comment by LeeThompson** [comment]
Configuration looks correct (secure is `false`). on the **network** tab the URLs are all _https_ and thus fail.   There is also a growing number of CORS failed messages.

It looks like the plugin is ignoring the _secure_ setting when creating URLs.

**Comment by baptistecdr** [comment]
Ok thanks, I still don't know what's going on :(

Do you have the same problem on Chrome/Chromium ?

**Comment by LeeThompson** [comment]
I set it up on Chrome (not my primary browser) and it works although it has a weird bug, when you add an entry it adds new characters to the front (as you type it's building the string backwards) so you need to save and edit.

**Comment by baptistecdr** [comment]
I added some debug message on this version: https://github.com/baptistecdr/aria2-integration/actions/runs/7151466041

Could you remove the current version, and install this one above using `about:debugging#/runtime/this-firefox` > `Load a temporary module...`

Click on `Examine` and go to the Console tab, then add your server in the extension's properties.
You should see some messages when clicking on Save.

https://github.com/baptistecdr/aria2-integration/compare/main...debug-message

**Comment by LeeThompson** [comment]
I'm not sure how to install the module from that, it said invalid manifest but I probably can't just put in the URL.

**Comment by baptistecdr** [comment]
I did a small video on how to install:


https://github.com/baptistecdr/aria2-integration/assets/11665396/7dd700d2-bcce-4c85-af23-6a9a53469cd5

**Comment by LeeThompson** [comment]
This is a bit messy, but here is the output.

```
TypeError: NetworkError when attempting to fetch resource. background.js:1:536
=== Server Configuration === background.js:1:290
Object { uuid: "1506797e-7b7a-4bf8-ace5-016e44a696f7", name: "NAS02", secure: false, host: "aria1.REDACTED", port: 8080, path: "/jsonrpc", secret: "", rpcParameters: {} }
background.js:1:334
http://aria1.REDACTED:8080/jsonrpc background.js:1:349
=== Doing a dummy HTTP request === background.js:1:379
=== Bad Request is expected === background.js:1:429
=== Server Configuration === background.js:1:290
Object { uuid: "c679d063-b2a4-4222-a133-847638daf154", name: "Localhost", secure: false, host: "localhost", port: 6800, path: "/jsonrpc", secret: "", rpcParameters: {} }
background.js:1:334
http://localhost:6800/jsonrpc background.js:1:349
=== Doing a dummy HTTP request === background.js:1:379
=== Bad Request is expected === background.js:1:429
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria1.REDACTED:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).
2
TypeError: NetworkError when attempting to fetch resource. background.js:1:536
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria1.REDACTED:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6800/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria1.REDACTED:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).
2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6800/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).
4
TypeError: NetworkError when attempting to fetch resource. background.js:1:536
=== Server Configuration === background.js:1:290
Object { uuid: "1506797e-7b7a-4bf8-ace5-016e44a696f7", name: "NAS02", secure: false, host: "aria1.REDACTED", port: 8080, path: "/jsonrpc", secret: "", rpcParameters: {} }
background.js:1:334
http://aria1.REDACTED:8080/jsonrpc background.js:1:349
=== Doing a dummy HTTP request === background.js:1:379
=== Bad Request is expected === background.js:1:429
=== Server Configuration === background.js:1:290
Object { uuid: "c679d063-b2a4-4222-a133-847638daf154", name: "NAS03", secure: false, host: "aria2.REDACTED", port: 8080, path: "/jsonrpc", secret: "", rpcParameters: {} }
background.js:1:334
http://aria2.REDACTED:8080/jsonrpc background.js:1:349
=== Doing a dummy HTTP request === background.js:1:379
=== Bad Request is expected ===
```

It spams these errors repeatedly:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria1.REDACTED:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria2.REDACTED:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria1.REDACTED:8080/jsonrpc. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://aria2.REDACTED:8080/jsonrpc. (Reason: CORS request 

```


I found these as yellow warnings, this may be what's changing it to https, I'm going to see if I can disable that.

```
Content-Security-Policy: Upgrading insecure request ‘http://aria1.REDACTED:8080/jsonrpc’ to use ‘https’
Content-Security-Policy: Upgrading insecure request ‘http://aria2.REDACTED:8080/jsonrpc’ to use ‘https’ 
```

**Comment by LeeThompson** [comment]
I don't quite understand why FIrefox is doing this change, I have HTTPS Only mode specifically disabled.

**Comment by baptistecdr** [comment]
The extension correctly setup the URL to HTTP, and indeed the problem comes from Firefox that change to HTTPS.

Maybe try to reset Firefox to default settings and install the extension ?

**Comment by LeeThompson** [comment]
They appear to have taken out the ability to disable this.

**Comment by LeeThompson** [comment]
An extension might be able to change the policy, not sure, the doc page is here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by LeeThompson** [comment]
I think I may need to set up some kind of HTTPS method to talk to Aria2 to use this.

**Comment by LeeThompson** [comment]
There *has* to be a way around this from the extension side, because the other Aria2 extension on the same firefox works fine.

**Comment by baptistecdr** [comment]
Yes, I will check the CSP policy of the extension

**Comment by Flute7** [comment]
I have exactly the same issue and the same CORS errors.

I have tested v4.0.0 and it works perfectly, so some change in the code between v4.0.0 an the current release is not playing nicely with Firefox.

I also have HTTPS-Only mode specifically turned off.

**Comment by baptistecdr** [comment]
I investigated last week without resolving this. I'm currently on vacation + Christmas arriving... I will continue to investigate after that.

**Comment by Flute7** [comment]
> I investigated last week without resolving this. I'm currently on vacation + Christmas arriving... I will continue to investigate after that.

Nice, happy to assist with troubleshooting anytime. Have a nice Christmas.

**Comment by baptistecdr** [comment]
Hi @LeeThompson @Flute7,

Happy Christmas and new year. I think I fixed the issue. Is it possible to test on your side?

You can find the binary here:
* https://github.com/baptistecdr/aria2-integration/actions/runs/7370986342

**Comment by LeeThompson** [comment]
It's actually talking to the aria instances so that's a good step!  I haven't tested it actually passing along downloads yet.

**Comment by baptistecdr** [comment]
Hello @LeeThompson and @Flute7,
4.7.4 is now available on Firefox & Chromium. It should fix the problem.
