### ISSUE TITLE
Feature Request - only capture downloads larger than X bytes

### ISSUE THREAD

**Issue by RobbedColek** [baptistecdr/aria2-integration#439]
Hello,

Thank you once again for quick response to my previous bug report!

I would like to request a feature, where the addon would only send downloads to Aria2 if file size exceeds some specific size.

The file size could be checked via HTTP HEAD request and checking Content-Length in response - but perhaps there's smarter way to check for this.

I'd find this feature very helpful for me, as I usually use Aria2 to download larger files and I'd like to keep downloading to my local storage smaller files (ex. saving some images from website - these are currently captured by addon).

**Comment by baptistecdr** [comment]
Hello,

Thank you for the feature request and the donation!

Interesting, I'll investigate how to implement that. The size of the file is ~~probably~~ given in the [DownloadItem](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/DownloadItem), it can be done quickly I guess. 🤙🏼 

Have a nice day,
Baptiste

**Comment by baptistecdr** [comment]
Just FYI, I'm still working on it but I'm struggling to get the fileSize, it works on Chromium but not Firefox...

**Comment by baptistecdr** [comment]
Sadly, the feature will be available only on Chromium, there is a bug on Mozilla side: https://bugzilla.mozilla.org/show_bug.cgi?id=1666137.

totalBytes/fileSIze is always -1 even when the download progress changes.

I will release a new version this week end.
