### ISSUE TITLE
"RPC Parameters" field in extension's options is not editable

### ISSUE THREAD

**Issue by stanwest** [baptistecdr/aria2-integration#532]
When viewing the extension's options in Firefox or Chrome, with a server tab selected, I cannot edit the "RPC Parameters" field; instead, it displays the fixed text "split: 5".

Versions are as follows:

*   Aria2 Integration: 4.9.3
*   Firefox: 126.0.1
*   Chrome: 125.0.6422.142

**Comment by baptistecdr** [comment]
Hello @stanwest,

Indeed, I will fix this. Thanks for the bug report!

Have a nice day,
baptistecdr

**Comment by baptistecdr** [comment]
* Aria2 Integration (4.9.4) has been released:
* For Firefox, the extesion is available now,
* for Chrome, the extension is in review,
* and for Edge, it will be available later on (probably next week).

**Comment by stanwest** [comment]
> Indeed, I will fix this. Thanks for the bug report!

You're welcome, and thanks for the speedy fix!
