### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RNavarro3000** [baptistecdr/aria2-integration#55]
Is it possible to support Firefox"Extension Shortcut" and Chrome "Keyboard Shortcut" feature to enable/disable "capture  downloads"?  Thanks.

**Comment by baptistecdr** [comment]
Hello @RNavarro3000 ,

With the new version (4.1.0), you can now use keyboard shortcut to toggle capture downloads.

Default shortcut is: Ctrl+Maj+D

If you have any problem, don't hesitate to open an issue!

Have a nice day,
baptistecdr

**Comment by RNavarro3000** [comment]
I will give it a try soon.  Thanks Baptistecdr!!
