### ISSUE TITLE
Could you add a keyboard shortcut to open this extension in Firefox?

### ISSUE THREAD

**Issue by kingfirewxm** [baptistecdr/aria2-integration#660]
I am a pretty heavy keyboard users and I hide my toolbar, it's difficult for me to unhide the toolbar and click the extension button. Could you add a keyboard shortcut to access this extension and show the popup?
Thanks in advance!

**Comment by baptistecdr** [comment]
The shortcut to open the popup has been added!

You can view the default assignation here: https://github.com/baptistecdr/aria2-integration/blob/main/public/manifest.json#L26

A new version of the extension has been released (v4.10.0) and It is now available on Firefox and later this week on Chrome/Edge (after a review by the respective entity).
