### ISSUE TITLE
Question: Purging downloads does not remove temporary files (download.file + download.file.aria2)

### ISSUE THREAD

**Issue by gokaybiz** [baptistecdr/aria2-integration#679]
Is this expected behavior? Shouldn't it supposed to remove pre-allocated files too?

To re-produce:
1-) Download a file named topkek.exe,
2-) Pause it (you can skip this step),
3-) Purge it 
4-) Check download location, you'll see allocated topkek.exe and topkek.exe.aria2 files (topkek.exe is broken indeed)

Thank you for your time.

**Comment by gokaybiz** [comment]
I think it's related with https://github.com/aria2/aria2/issues/728

**Comment by baptistecdr** [comment]
Hello @gokaybiz,

It seems to be related to Aria2 as described in the issue that you linked.

There is nothing I can do on my side since I rely 100% on Aria2 API...
