### ISSUE TITLE
download links via the context menus not work

### ISSUE THREAD

**Issue by kai456789** [baptistecdr/aria2-integration#682]
upgrade to iceweasel 132.0.2

download links via the context menus function disappears

But the kit itself functions fine

**Comment by baptistecdr** [comment]
Hello @kai456789,

Hum, I didn't know the existence of `iceweasel`, so I look up a bit... It seems to be a Firefox version.

I didn't found how to insall it on macOS or PopOS (ubuntu) so it will be difficult to debug.

On your side, you can go on `about:debugging#/runtime/this-firefox` > `Examinate` on my extension. A window should open and you can click on the `Console` tab.

Reload a Web page on you browser to check if any errors comes up.

**Comment by kai456789** [comment]
> Hello @kai456789,
> 
> Hum, I didn't know the existence of `iceweasel`, so I look up a bit... It seems to be a Firefox version.
> 
> I didn't found how to insall it on macOS or PopOS (ubuntu) so it will be difficult to debug.
> 
> On your side, you can go on `about:debugging#/runtime/this-firefox` > `Examinate` on my extension. A window should open and you can click on the `Console` tab.
> 
> Reload a Web page on you browser to check if any errors comes up.

The next day, after restarting the computer, the issue disappeared.
